import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    // Landing Page
    'landing.title': 'إدارة مشاريع الطرق',
    'landing.subtitle': 'منصة متكاملة ومتقدمة لإدارة مشاريع البنية التحتية للطرق في المملكة العربية السعودية',
    'landing.getStarted': 'ابدأ الآن',
    'landing.watchDemo': 'شاهد العرض',
    'landing.secure': 'آمن',
    'landing.fast': 'سريع',
    'landing.easy': 'سهل',
    'landing.quality': 'جودة',
    'landing.roadProjects': 'مشاريع الطرق',
    'landing.engineers': 'المهندسون',
    'landing.uptime': 'وقت التشغيل',
    'landing.support': 'الدعم',
    'landing.header': 'نظام مشاريع الطرق',
    'landing.headerSub': 'الهيئة العامة للطرق',
    'landing.users': '500+ مستخدم',
    
    // Auth
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.role': 'الدور الوظيفي',
    'auth.signInBtn': 'تسجيل الدخول',
    'auth.signUpBtn': 'إنشاء حساب جديد',
    'auth.loading': 'جاري التحميل...',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.loginError': 'خطأ في تسجيل الدخول',
    'auth.signupSuccess': 'تم إنشاء الحساب بنجاح',
    'auth.signupError': 'خطأ في إنشاء الحساب',
    'auth.systemTitle': 'نظام إدارة مشاريع الطرق',
    'auth.systemSubtitle': 'الهيئة العامة للطرق - المملكة العربية السعودية 🇸🇦',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً',
    'dashboard.overview': 'إليك نظرة سريعة على مشاريع الطرق اليوم',
    'dashboard.home': 'الرئيسية',
    'dashboard.projects': 'المشاريع',
    'dashboard.newProject': 'مشروع جديد',
    'dashboard.reports': 'بيان النسب',
    'dashboard.daily': 'التقارير اليومية',
    'dashboard.ai': 'المساعد الذكي',
    'dashboard.users': 'المستخدمين',
    'dashboard.logout': 'تسجيل الخروج',
    'dashboard.settings': 'الإعدادات',
    'dashboard.title': 'نظام إدارة مشاريع الطرق',
    'dashboard.subtitle': 'الهيئة العامة للطرق',
    'dashboard.user': 'المستخدم',
    'dashboard.defaultRole': 'مستخدم',
    'dashboard.statsLoadError': 'خطأ في تحميل الإحصائيات',
    
    // Stats
    'stats.totalProjects': 'إجمالي المشاريع',
    'stats.activeProjects': 'المشاريع النشطة',
    'stats.completedProjects': 'المشاريع المكتملة',
    'stats.avgProgress': 'متوسط الإنجاز',
    'stats.allProjects': 'جميع المشاريع المسجلة',
    'stats.inProgress': 'قيد التنفيذ حالياً',
    'stats.completedSuccess': 'تم إنجازها بنجاح',
    'stats.overallProgress': 'نسبة الإنجاز العامة',
    
    // Actions
    'actions.quickActions': 'الإجراءات السريعة',
    'actions.createProject': 'إنشاء مشروع جديد',
    'actions.addReport': 'تسجيل تقرير يومي',
    'actions.viewReports': 'عرض التقارير',
    'actions.recentProjects': 'المشاريع الأخيرة',
    'actions.viewAll': 'عرض الكل',
    'actions.back': 'رجوع',
    'actions.manageUsers': 'إدارة المستخدمين',
    'actions.performanceContracts': 'عقود الأداء',
    
    // Projects
    'projects.list': 'قائمة المشاريع',
    'projects.create': 'إنشاء مشروع',
    'projects.details': 'تفاصيل لمشروع',
    'projects.edit': 'تعديل المشروع',
    'projects.delete': 'حذف المشروع',
    'projects.deleteConfirm': 'هل أنت متأكد من حذف هذا المشروع؟',
    'projects.deleteSuccess': 'تم حذف المشروع بنجاح',
    'projects.deleteFailed': 'فشل حذف المشروع',
    'projects.roadName': 'اسم الطريق',
    'projects.region': 'المنطقة',
    'projects.branch': 'الفرع',
    'projects.type': 'نوع المشروع',
    'projects.value': 'قيمة المشروع',
    'projects.duration': 'المدة',
    'projects.progress': 'نسبة الإنجاز',
    'projects.status': 'الحالة',
    'projects.actualProgress': 'التقدم الفعلي',
    'projects.plannedProgress': 'التقدم المخطط',
    'projects.deviation': 'الانحراف',
    'projects.noProjects': 'لا توجد مشاريع',
    'projects.loading': 'جاري تحميل المشاريع...',
    'projects.filter': 'تصفية',
    'projects.search': 'بحث...',
    'projects.year': 'السنة',
    'projects.projectNumber': 'رقم المشروع',
    'projects.contractValue': 'قيمة العقد',
    'projects.workDescription': 'وصف العمل',
    'projects.siteHandoverDate': 'تاريخ تسليم الموقع',
    'projects.contractEndDate': 'تاريخ انتهاء العقد',
    'projects.implementation': 'تنفيذ',
    'projects.maintenance': 'صيانة',
    'projects.month': 'شهر',
    'projects.months': 'شهور',
    'projects.sar': 'ر.س',
    'projects.million': 'م',
    
    // Reports
    'reports.daily': 'التقارير اليومية',
    'reports.progress': 'بيان النسب',
    'reports.add': 'إضافة تقرير',
    'reports.view': 'عرض التقارير',
    'reports.export': 'تصدير',
    'reports.exportExcel': 'تصدير Excel',
    'reports.exportPDF': 'تصدير PDF',
    'reports.exportWord': 'تصدير Word',
    'reports.filters': 'الفلاتر',
    'reports.clearFilters': 'مسح الفلاتر',
    'reports.all': 'الكل',
    'reports.allRegions': 'جميع المناطق',
    'reports.allStatus': 'جميع الحالات',
    'reports.allTypes': 'جميع الأنواع',
    'reports.completed': 'منجز',
    'reports.inProgress': 'جاري',
    'reports.delayed': 'متأخر',
    'reports.totalProjects': 'إجمالي المشاريع',
    'reports.reportTitle': 'بيان نسب الإنجاز',
    'reports.issueDate': 'تاريخ الإصدار',
    'reports.footer': 'الهيئة العامة للطرق - المملكة العربية السعودية 🇸🇦',
    
    // Create Project
    'create.title': 'إنشاء مشروع جديد',
    'create.basicInfo': 'المعلومات الرئيسية',
    'create.workOrderDescription': 'وصف أمر العمل',
    'create.workOrderNumber': 'رقم أمر العمل / التبليغ',
    'create.roadName': 'اسم الطريق',
    'create.roadNumber': 'رقم الطريق',
    'create.region': 'المنطقة',
    'create.branch': 'الفرع',
    'create.projectNumber': 'رقم المشروع',
    'create.year': 'العام',
    'create.financialInfo': 'المعلومات المالية',
    'create.projectValue': 'قيمة التبليغ (ريال)',
    'create.duration': 'مدة التنفيذ (شهور)',
    'create.dates': 'التواريخ',
    'create.siteHandoverDate': 'تاريخ تسليم الموقع',
    'create.contractEndDate': 'تاريخ نهاية المدة التعاقدية',
    'create.progress': 'نسب الإنجاز',
    'create.progressActual': 'نسبة الإنجاز الفعلي (%)',
    'create.progressPlanned': 'النسبة المفترض إنجازها حسب البرنامج (%)',
    'create.deviation': 'التقدم / نسبة التأخير (%)',
    'create.projectType': 'نوع المشروع',
    'create.implementation': 'تنفيذ',
    'create.maintenance': 'صيانة',
    'create.status': 'حالة المشروع',
    'create.statusOngoing': 'جاري العمل',
    'create.statusStalled': 'متعثر',
    'create.statusStopped': 'متوقف',
    'create.statusPreliminary': 'تم التسليم الابتدائي',
    'create.statusFinal': 'تم الرفع بالاستلام النهائي',
    'create.notes': 'الملاحظات',
    'create.images': 'صور المشروع (اختياري)',
    'create.uploadImages': 'رفع الصور',
    'create.selectImages': 'اختر صور للمشروع',
    'create.submit': 'إنشاء المشروع',
    'create.cancel': 'إلغاء',
    'create.creating': 'جاري الإنشاء...',
    'create.success': 'تم إنشاء المشروع بنجاح!',
    'create.error': 'حدث خطأ أثناء إنشاء المشروع',
    'create.items': 'بنود المشروع',
    'create.addItem': 'إضافة بند',
    'create.itemType': 'نوع البند',
    'create.itemNumber': 'رقم البند',
    'create.itemName': 'اسم البند',
    'create.itemTypePlaceholder': 'مثال: أعمال الحفر',
    'create.itemNumberPlaceholder': 'مثال: 101',
    'create.itemNamePlaceholder': 'مثال: إزالة طبقة الأسفلت',
    'create.removeItem': 'حذف البند',

    // Projects List
    'projects.title': 'جميع المشاريع',
    'projects.noProjects': 'لا توجد مشاريع',
    'projects.startCreating': 'ابدأ بإنشاء مشروع جديد',
    'projects.projectNumber': 'رقم المشروع',
    'projects.year': 'السنة',
    'projects.value': 'القيمة',
    'projects.million': 'م.ر',
    'projects.progress': 'الإنجاز',
    'projects.delete': 'حذف المشروع',
    'projects.confirmDelete': 'هل أنت متأكد؟',
    'projects.confirmDeleteDesc': 'سيتم حذف المشروع نهائياً ولا يمكن التراجع عن هذا الإجراء',
    'projects.cancel': 'إلغاء',
    'projects.deleteSuccess': 'تم حذف المشروع بنجاح',
    'projects.deleteError': 'حدث خطأ أثناء حذف المشروع',

    // Daily Reports
    'daily.title': 'التقارير اليومية',
    'daily.createReport': 'إنشاء تقرير يومي',
    'daily.selectProject': 'اختر المشروع',
    'daily.selectProjectPlaceholder': 'حدد المشروع',
    'daily.date': 'التاريخ',
    'daily.workDescription': 'وصف الأعمال المنجزة',
    'daily.workDescriptionPlaceholder': 'اكتب تفاصيل الأعمال المنجزة اليوم',
    'daily.equipment': 'المعدات المستخدمة',
    'daily.equipmentPlaceholder': 'قائمة بالمعدات المستخدمة',
    'daily.workers': 'عدد العمال',
    'daily.weather': 'حالة الطقس',
    'daily.weatherPlaceholder': 'وصف حالة الطقس',
    'daily.issues': 'المشاكل والملاحظات',
    'daily.issuesPlaceholder': 'أي مشاكل أو ملاحظات',
    'daily.submit': 'حفظ التقرير',
    'daily.cancel': 'إلغاء',
    'daily.creating': 'جاري الحفظ...',
    'daily.success': 'تم حفظ التقرير بنجاح',
    'daily.error': 'حدث خطأ أثناء حفظ التقرير',
    'daily.noReports': 'لا توجد تقارير',
    'daily.startCreatingReports': 'ابدأ بإنشاء تقرير يومي جديد',
    'daily.viewReports': 'عرض التقارير',
    'daily.project': 'المشروع',
    'daily.reportDate': 'تاريخ التقرير',

    // Progress Statement (بيان النسب)
    'statement.title': 'بيان نسب الإنجاز',
    'statement.export': 'تصدير',
    'statement.exportExcel': 'Excel',
    'statement.exportPDF': 'PDF',
    'statement.exportWord': 'Word',
    'statement.workOrderNumber': 'رقم أمر العمل',
    'statement.year': 'العام',
    'statement.type': 'النوع',
    'statement.roadNumber': 'رقم الطريق',
    'statement.roadName': 'اسم الطريق',
    'statement.description': 'وصف أمر العمل',
    'statement.duration': 'المدة (شهور)',
    'statement.siteHandoverDate': 'تاريخ تسليم الموقع',
    'statement.contractEndDate': 'تاريخ نهاية المدة',
    'statement.actualProgress': 'الإنجاز الفعلي %',
    'statement.plannedProgress': 'المفترض %',
    'statement.deviation': 'التقدم/التأخير %',
    'statement.status': 'الحالة',
    'statement.branch': 'الفرع',
    'statement.region': 'المنطقة',
    'statement.value': 'قيمة التبليغ (ريال)',
    'statement.notes': 'الملاحظات',
    'statement.noData': 'لا توجد بيانات',
    'statement.loading': 'جاري التحميل...',
    'statement.exportSuccess': 'تم التصدير بنجاح',
    'statement.exportError': 'حدث خطأ أثناء التصدير',

    // AI Assistant
    'ai.title': 'المساعد الذكي',
    'ai.welcome': 'مرحباً! كيف يمكنني مساعدتك في إدارة مشاريع الطرق؟',
    'ai.placeholder': 'اكتب رسالتك هنا...',
    'ai.send': 'إرسال',
    'ai.sending': 'جاري الإرسال...',
    'ai.createProject': 'إنشاء مشروع من الوصف',
    'ai.analyzeImage': 'تحليل صورة',
    'ai.uploadImage': 'رفع صورة',
    'ai.generating': 'جاري التحليل...',

    // User Management
    'users.title': 'إدارة المستخدمين',
    'users.addUser': 'إضافة مستخدم جديد',
    'users.createUser': 'إنشاء مستخدم جديد',
    'users.createUserDesc': 'أدخل معلومات المستخدم الجديد لإضافته إلى النظام',
    'users.fullName': 'الاسم الكامل',
    'users.email': 'البريد الإلكتروني',
    'users.password': 'كلمة المرور',
    'users.role': 'الدور الوظيفي',
    'users.roleGeneralManager': 'مدير عام',
    'users.roleBranchGeneralManager': 'مدير عام الفرع',
    'users.roleAdminManager': 'مدير إداري',
    'users.roleProjectManager': 'مدير مشروع',
    'users.roleSupervisorEngineer': 'مهندس مشرف',
    'users.roleEngineer': 'مهندس',
    'users.roleObserver': 'مراقب',
    'users.submit': 'إنشاء المستخدم',
    'users.actions': 'الإجراءات',
    'users.createdAt': 'تاريخ الإنشاء',
    'users.noUsers': 'لا يوجد مستخدمين',
    'users.loading': 'جاري التحميل...',
    'users.totalUsers': 'إجمالي المستخدمين',
    'users.generalManagers': 'مدراء عامون',
    'users.projectManagers': 'مدراء مشاريع',
    'users.engineers': 'مهندسين',
    'users.unauthorized': 'غير مصرح',
    'users.unauthorizedDesc': 'هذه الصفحة متاحة للمدير العام فقط',
    
    // Roles
    'role.generalManager': 'مدير عام',
    'role.branchGeneralManager': 'مدير عام الفرع',
    'role.adminManager': 'مدير إداري',
    'role.supervisorEngineer': 'مهندس مشرف',
    'role.engineer': 'مهندس',
    'role.observer': 'مراقب',
    
    // Permissions
    'permission.readOnly': 'عرض فقط',
    'permission.noEditAccess': 'ليس لديك صلاحية التعديل',
    'permission.adminOnly': 'هذه الميزة متاحة للمدير الإداري فقط',
    
    // Daily Reports
    'daily.title': 'Daily Reports',
    'daily.add': 'Add Daily Report',
    'daily.list': 'Reports List',
    'daily.date': 'Date',
    'daily.project': 'Project',
    'daily.workDone': 'Work Done',
    'daily.issues': 'Issues',
    'daily.notes': 'Notes',
    'daily.addError': 'Error adding report',
    'daily.addSuccess': 'Report added successfully',
    
    // Common
    'common.allRightsReserved': 'جميع الحقوق محفوظة',
    'common.saudiArabia': 'المملكة العربية السعودية',
    'common.login': 'تسجيل الدخول',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.loading': 'جاري التحيل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.warning': 'تحذير',
    'common.info': 'معلومات',
    'common.notSpecified': 'غير محدد',
    'common.search': 'بحث',
    'common.filter': 'فلتر',
    'common.export': 'تصدير',
    'common.print': 'طباعة',
    'common.download': 'تحميل',
  },
  en: {
    // Landing Page
    'landing.title': 'Road Projects Management',
    'landing.subtitle': 'An integrated and advanced platform for managing road infrastructure projects in Saudi Arabia',
    'landing.getStarted': 'Get Started',
    'landing.watchDemo': 'Watch Demo',
    'landing.secure': 'Secure',
    'landing.fast': 'Fast',
    'landing.easy': 'Easy',
    'landing.quality': 'Quality',
    'landing.roadProjects': 'Road Projects',
    'landing.engineers': 'Engineers',
    'landing.uptime': 'Uptime',
    'landing.support': 'Support',
    'landing.header': 'Road Projects System',
    'landing.headerSub': 'Roads General Authority',
    'landing.users': '500+ Users',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.role': 'Role',
    'auth.signInBtn': 'Sign In',
    'auth.signUpBtn': 'Create New Account',
    'auth.loading': 'Loading...',
    'auth.loginSuccess': 'Login successful',
    'auth.loginError': 'Login error',
    'auth.signupSuccess': 'Account created successfully',
    'auth.signupError': 'Account creation error',
    'auth.systemTitle': 'Road Projects Management System',
    'auth.systemSubtitle': 'Roads General Authority - Kingdom of Saudi Arabia 🇸🇦',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Here\'s a quick overview of today\'s road projects',
    'dashboard.home': 'Home',
    'dashboard.projects': 'Projects',
    'dashboard.newProject': 'New Project',
    'dashboard.reports': 'Progress Report',
    'dashboard.daily': 'Daily Reports',
    'dashboard.ai': 'AI Assistant',
    'dashboard.users': 'Users',
    'dashboard.logout': 'Logout',
    'dashboard.settings': 'Settings',
    'dashboard.title': 'Road Projects Management System',
    'dashboard.subtitle': 'Roads General Authority',
    'dashboard.user': 'User',
    'dashboard.defaultRole': 'User',
    'dashboard.statsLoadError': 'Error loading statistics',
    
    // Stats
    'stats.totalProjects': 'Total Projects',
    'stats.activeProjects': 'Active Projects',
    'stats.completedProjects': 'Completed Projects',
    'stats.avgProgress': 'Average Progress',
    'stats.allProjects': 'All registered projects',
    'stats.inProgress': 'Currently in progress',
    'stats.completedSuccess': 'Successfully completed',
    'stats.overallProgress': 'Overall progress percentage',
    
    // Actions
    'actions.quickActions': 'Quick Actions',
    'actions.createProject': 'Create New Project',
    'actions.addReport': 'Add Daily Report',
    'actions.viewReports': 'View Reports',
    'actions.recentProjects': 'Recent Projects',
    'actions.viewAll': 'View All',
    'actions.back': 'Back',
    'actions.manageUsers': 'Manage Users',
    'actions.performanceContracts': 'Performance Contracts',
    
    // Projects
    'projects.list': 'Projects List',
    'projects.create': 'Create Project',
    'projects.details': 'Project Details',
    'projects.edit': 'Edit Project',
    'projects.delete': 'Delete Project',
    'projects.deleteConfirm': 'Are you sure you want to delete this project?',
    'projects.deleteSuccess': 'Project deleted successfully',
    'projects.deleteFailed': 'Failed to delete project',
    'projects.roadName': 'Road Name',
    'projects.region': 'Region',
    'projects.branch': 'Branch',
    'projects.type': 'Project Type',
    'projects.value': 'Project Value',
    'projects.duration': 'Duration',
    'projects.progress': 'Progress',
    'projects.status': 'Status',
    'projects.actualProgress': 'Actual Progress',
    'projects.plannedProgress': 'Planned Progress',
    'projects.deviation': 'Deviation',
    'projects.noProjects': 'No projects found',
    'projects.loading': 'Loading projects...',
    'projects.filter': 'Filter',
    'projects.search': 'Search...',
    'projects.year': 'Year',
    'projects.projectNumber': 'Project Number',
    'projects.contractValue': 'Contract Value',
    'projects.workDescription': 'Work Description',
    'projects.siteHandoverDate': 'Site Handover Date',
    'projects.contractEndDate': 'Contract End Date',
    'projects.implementation': 'Implementation',
    'projects.maintenance': 'Maintenance',
    'projects.month': 'Month',
    'projects.months': 'Months',
    'projects.sar': 'SAR',
    'projects.million': 'M',
    
    // Reports
    'reports.daily': 'Daily Reports',
    'reports.progress': 'Progress Report',
    'reports.add': 'Add Report',
    'reports.view': 'View Reports',
    'reports.export': 'Export',
    'reports.exportExcel': 'Export Excel',
    'reports.exportPDF': 'Export PDF',
    'reports.exportWord': 'Export Word',
    'reports.filters': 'Filters',
    'reports.clearFilters': 'Clear Filters',
    'reports.all': 'All',
    'reports.allRegions': 'All Regions',
    'reports.allStatus': 'All Status',
    'reports.allTypes': 'All Types',
    'reports.completed': 'Completed',
    'reports.inProgress': 'In Progress',
    'reports.delayed': 'Delayed',
    'reports.totalProjects': 'Total Projects',
    'reports.reportTitle': 'Progress Report',
    'reports.issueDate': 'Issue Date',
    'reports.footer': 'Roads General Authority - Kingdom of Saudi Arabia 🇸🇦',
    
    // Create Project
    'create.title': 'Create New Project',
    'create.basicInfo': 'Basic Information',
    'create.workOrderDescription': 'Work Order Description',
    'create.workOrderNumber': 'Work Order Number / Notice',
    'create.roadName': 'Road Name',
    'create.roadNumber': 'Road Number',
    'create.region': 'Region',
    'create.branch': 'Branch',
    'create.projectNumber': 'Project Number',
    'create.year': 'Year',
    'create.financialInfo': 'Financial Information',
    'create.projectValue': 'Notice Value (SAR)',
    'create.duration': 'Execution Duration (Months)',
    'create.dates': 'Dates',
    'create.siteHandoverDate': 'Site Handover Date',
    'create.contractEndDate': 'Contract End Date',
    'create.progress': 'Progress Percentages',
    'create.progressActual': 'Actual Progress (%)',
    'create.progressPlanned': 'Planned Progress (%)',
    'create.deviation': 'Progress / Delay Percentage (%)',
    'create.projectType': 'Project Type',
    'create.implementation': 'Implementation',
    'create.maintenance': 'Maintenance',
    'create.status': 'Project Status',
    'create.statusOngoing': 'Ongoing',
    'create.statusStalled': 'Stalled',
    'create.statusStopped': 'Stopped',
    'create.statusPreliminary': 'Preliminary Handover',
    'create.statusFinal': 'Final Handover',
    'create.notes': 'Notes',
    'create.images': 'Project Images (Optional)',
    'create.uploadImages': 'Upload Images',
    'create.selectImages': 'Select project images',
    'create.submit': 'Create Project',
    'create.cancel': 'Cancel',
    'create.creating': 'Creating...',
    'create.success': 'Project created successfully!',
    'create.error': 'Error creating project',
    'create.items': 'Project Items',
    'create.addItem': 'Add Item',
    'create.itemType': 'Item Type',
    'create.itemNumber': 'Item Number',
    'create.itemName': 'Item Name',
    'create.itemTypePlaceholder': 'Example: Excavation Work',
    'create.itemNumberPlaceholder': 'Example: 101',
    'create.itemNamePlaceholder': 'Example: Removal of Bottom Layer',
    'create.removeItem': 'Remove Item',
    
    // AI Assistant
    'ai.title': 'AI Assistant',
    'ai.askQuestion': 'Ask a Question',
    'ai.send': 'Send',
    'ai.thinking': 'Thinking...',
    'ai.placeholder': 'Type your question here...',
    'ai.welcome': 'Hello! How can I help you today?',
    'ai.createFromDescription': 'Create Project from Description',
    'ai.analyzeImage': 'Analyze Image',
    'ai.suggestions': 'Suggestions',
    'ai.error': 'An error occurred in AI Assistant',
    'ai.projectCreated': '✅ **Project created successfully!**',
    'ai.projectError': '❌ Sorry, an error occurred while creating the project. Please try again.',
    
    // Users
    'users.management': 'Users Management',
    'users.add': 'Add User',
    'users.addNew': 'Add New User',
    'users.list': 'Users List',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.actions': 'Actions',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.createUser': 'Create User',
    'users.fullName': 'Full Name',
    'users.password': 'Password',
    'users.selectRole': 'Select Role',
    'users.creating': 'Creating...',
    'users.enterInfo': 'Enter new user information to add them to the system',
    'users.totalUsers': 'Total Users',
    'users.noUsers': 'No users found',
    'users.loadError': 'Error loading users',
    'users.createSuccess': 'User created successfully',
    'users.createError': 'Error creating user',
    'users.newUserTitle': 'Create New User',
    
    // Roles
    'role.generalManager': 'General Manager',
    'role.branchGeneralManager': 'Branch General Manager',
    'role.adminManager': 'Admin Manager',
    'role.supervisorEngineer': 'Supervising Engineer',
    'role.engineer': 'Engineer',
    'role.observer': 'Observer',
    
    // Permissions
    'permission.readOnly': 'Read Only',
    'permission.noEditAccess': 'You do not have edit access',
    'permission.adminOnly': 'This feature is available to Admin Manager only',
    
    // Daily Reports
    'daily.title': 'Daily Reports',
    'daily.add': 'Add Daily Report',
    'daily.list': 'Reports List',
    'daily.date': 'Date',
    'daily.project': 'Project',
    'daily.workDone': 'Work Done',
    'daily.issues': 'Issues',
    'daily.notes': 'Notes',
    'daily.addError': 'Error adding report',
    'daily.addSuccess': 'Report added successfully',
    
    // Common
    'common.allRightsReserved': 'All Rights Reserved',
    'common.saudiArabia': 'Kingdom of Saudi Arabia',
    'common.login': 'Login',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.notSpecified': 'Not Specified',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.print': 'Print',
    'common.download': 'Download',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};