DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS performance_contracts CASCADE;
DROP TABLE IF EXISTS percentage_statements CASCADE;
DROP TABLE IF EXISTS daily_reports CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS users CASCADE;
